// <auto-generated />
using System;
using HappyPrograming.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyPrograming.Migrations
{
    [DbContext(typeof(HappyprogrammingContext))]
    partial class HappyprogrammingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HappyPrograming.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_feature");

                    b.ToTable("feature", (string)null);
                });

            modelBuilder.Entity("HappyPrograming.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MenteeId")
                        .HasColumnType("int")
                        .HasColumnName("mentee_id");

                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<double>("RatingStar")
                        .HasColumnType("float")
                        .HasColumnName("rating_star");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.HasKey("Id")
                        .HasName("pk_feedback");

                    b.HasIndex("MenteeId");

                    b.HasIndex("MentorId");

                    b.HasIndex(new[] { "RequestId", "MenteeId" }, "uq_feedback_mentee")
                        .IsUnique();

                    b.ToTable("feedback", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Rất nhiệt tình!",
                            CreatedAt = new DateTime(2026, 3, 22, 11, 55, 23, 21, DateTimeKind.Local).AddTicks(681),
                            MenteeId = 6,
                            MentorId = 1,
                            RatingStar = 5.0,
                            RequestId = 5
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Giải thích dễ hiểu.",
                            CreatedAt = new DateTime(2026, 3, 22, 11, 55, 23, 21, DateTimeKind.Local).AddTicks(685),
                            MenteeId = 6,
                            MentorId = 1,
                            RatingStar = 4.0,
                            RequestId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Cảm ơn anh Khoa đã giúp!",
                            CreatedAt = new DateTime(2026, 3, 22, 11, 55, 23, 21, DateTimeKind.Local).AddTicks(688),
                            MenteeId = 3,
                            MentorId = 1,
                            RatingStar = 5.0,
                            RequestId = 1
                        });
                });

            modelBuilder.Entity("HappyPrograming.Models.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("profession");

                    b.Property<string>("ProfessionIntroduction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("profession_introduction");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("service_description");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mentor");

                    b.HasIndex(new[] { "UserId" }, "UQ__mentor__B9BE370EC682AD34")
                        .IsUnique();

                    b.ToTable("mentor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Profession = "Senior .NET Developer",
                            ProfessionIntroduction = "5 years of experience",
                            ServiceDescription = "Teaching C# and EF Core",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Profession = "Frontend Specialist",
                            ProfessionIntroduction = "ReactJS Expert",
                            ServiceDescription = "Teaching React and UI/UX",
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Profession = "Data Scientist",
                            ProfessionIntroduction = "Python Specialist",
                            ServiceDescription = "Teaching SQL and ML",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("HappyPrograming.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int")
                        .HasColumnName("creator_id");

                    b.Property<DateOnly>("Deadlinedate")
                        .HasColumnType("date")
                        .HasColumnName("deadlinedate");

                    b.Property<int>("Deadlinehour")
                        .HasColumnType("int")
                        .HasColumnName("deadlinehour");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_request");

                    b.HasIndex("CreatorId");

                    b.ToTable("request", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Fix bug scaffold.",
                            CreatorId = 3,
                            Deadlinedate = new DateOnly(2026, 4, 1),
                            Deadlinehour = 2,
                            Status = "Open",
                            Title = "Lỗi kết nối DbContext"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Lộ trình học React.",
                            CreatorId = 6,
                            Deadlinedate = new DateOnly(2026, 4, 15),
                            Deadlinehour = 10,
                            Status = "Processing",
                            Title = "Học ReactJS từ đầu"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Review câu lệnh JOIN.",
                            CreatorId = 7,
                            Deadlinedate = new DateOnly(2026, 3, 25),
                            Deadlinehour = 5,
                            Status = "Open",
                            Title = "Tối ưu câu lệnh SQL"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Góp ý kiến trúc.",
                            CreatorId = 3,
                            Deadlinedate = new DateOnly(2026, 5, 10),
                            Deadlinehour = 20,
                            Status = "Open",
                            Title = "Review đồ án"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Build container cho .NET.",
                            CreatorId = 6,
                            Deadlinedate = new DateOnly(2026, 4, 20),
                            Deadlinehour = 3,
                            Status = "Closed",
                            Title = "Docker căn bản"
                        });
                });

            modelBuilder.Entity("HappyPrograming.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex(new[] { "Name" }, "UQ__role__72E12F1B718CD346")
                        .IsUnique();

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mentor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mentee"
                        });
                });

            modelBuilder.Entity("HappyPrograming.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_skill");

                    b.ToTable("skill", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Basic to Advanced C#",
                            Name = "C# Programming",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Java Core",
                            Name = "Java",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Database Management",
                            Name = "SQL Server",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("HappyPrograming.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone_number");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "EmailAddress" }, "UQ__user__20C6DFF58201DFF5")
                        .IsUnique();

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__user__A1936A6B0E0D7E03")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__user__F3DBC572F13F87AC")
                        .IsUnique();

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 11, 55, 23, 21, DateTimeKind.Local).AddTicks(286),
                            Dob = new DateOnly(1990, 1, 1),
                            EmailAddress = "admin@happy.com",
                            FirstName = "Admin",
                            Gender = "Other",
                            LastName = "System",
                            Password = "password123",
                            PhoneNumber = "0123456789",
                            RoleId = 1,
                            Status = "Active",
                            Username = "admin01"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 22, 11, 55, 23, 21, DateTimeKind.Local).AddTicks(303),
                            Dob = new DateOnly(1995, 5, 20),
                            EmailAddress = "khoa@mentor.com",
                            FirstName = "Khoa",
                            Gender = "Male",
                            LastName = "Nguyen",
                            Password = "password123",
                            PhoneNumber = "0987654321",
                            RoleId = 2,
                            Status = "Active",
                            Username = "mentor_khoa"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 22, 11, 55, 23, 21, DateTimeKind.Local).AddTicks(308),
                            Dob = new DateOnly(2002, 10, 15),
                            EmailAddress = "an@mentee.com",
                            FirstName = "An",
                            Gender = "Female",
                            LastName = "Tran",
                            Password = "password123",
                            PhoneNumber = "0909090909",
                            RoleId = 3,
                            Status = "Active",
                            Username = "mentee_an"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 22, 11, 55, 23, 21, DateTimeKind.Local).AddTicks(314),
                            Dob = new DateOnly(1992, 3, 10),
                            EmailAddress = "lan.hoang@mentor.com",
                            FirstName = "Lan",
                            Gender = "Female",
                            LastName = "Hoang",
                            Password = "password123",
                            PhoneNumber = "0911223344",
                            RoleId = 2,
                            Status = "Active",
                            Username = "mentor_lan"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 22, 11, 55, 23, 21, DateTimeKind.Local).AddTicks(318),
                            Dob = new DateOnly(1988, 8, 25),
                            EmailAddress = "minh.vu@mentor.com",
                            FirstName = "Minh",
                            Gender = "Male",
                            LastName = "Vu",
                            Password = "password123",
                            PhoneNumber = "0922334455",
                            RoleId = 2,
                            Status = "Active",
                            Username = "mentor_minh"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 22, 11, 55, 23, 21, DateTimeKind.Local).AddTicks(323),
                            Dob = new DateOnly(2003, 1, 12),
                            EmailAddress = "long.phi@mentee.com",
                            FirstName = "Long",
                            Gender = "Male",
                            LastName = "Phi",
                            Password = "password123",
                            PhoneNumber = "0933445566",
                            RoleId = 3,
                            Status = "Active",
                            Username = "mentee_long"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 22, 11, 55, 23, 21, DateTimeKind.Local).AddTicks(328),
                            Dob = new DateOnly(2004, 11, 30),
                            EmailAddress = "vy.le@mentee.com",
                            FirstName = "Vy",
                            Gender = "Female",
                            LastName = "Le",
                            Password = "password123",
                            PhoneNumber = "0944556677",
                            RoleId = 3,
                            Status = "Active",
                            Username = "mentee_vy"
                        });
                });

            modelBuilder.Entity("MentorRequest", b =>
                {
                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.HasKey("MentorId", "RequestId")
                        .HasName("pk_mentorrequest");

                    b.HasIndex("RequestId");

                    b.ToTable("mentor_request", (string)null);

                    b.HasData(
                        new
                        {
                            MentorId = 1,
                            RequestId = 2
                        },
                        new
                        {
                            MentorId = 1,
                            RequestId = 3
                        });
                });

            modelBuilder.Entity("MentorSkill", b =>
                {
                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.HasKey("MentorId", "SkillId")
                        .HasName("pk_mentorskill");

                    b.HasIndex("SkillId");

                    b.ToTable("mentor_skill", (string)null);

                    b.HasData(
                        new
                        {
                            MentorId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            MentorId = 1,
                            SkillId = 3
                        },
                        new
                        {
                            MentorId = 3,
                            SkillId = 3
                        });
                });

            modelBuilder.Entity("RequestSkill", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.HasKey("RequestId", "SkillId")
                        .HasName("pk_requestskill");

                    b.HasIndex("SkillId");

                    b.ToTable("request_skill", (string)null);

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            SkillId = 1
                        },
                        new
                        {
                            RequestId = 1,
                            SkillId = 3
                        },
                        new
                        {
                            RequestId = 4,
                            SkillId = 1
                        },
                        new
                        {
                            RequestId = 3,
                            SkillId = 3
                        });
                });

            modelBuilder.Entity("RoleFeature", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int")
                        .HasColumnName("feature_id");

                    b.HasKey("RoleId", "FeatureId")
                        .HasName("pk_rolefeature");

                    b.HasIndex("FeatureId");

                    b.ToTable("role_feature", (string)null);
                });

            modelBuilder.Entity("HappyPrograming.Models.Feedback", b =>
                {
                    b.HasOne("HappyPrograming.Models.User", "Mentee")
                        .WithMany("Feedbacks")
                        .HasForeignKey("MenteeId")
                        .IsRequired()
                        .HasConstraintName("fk_feedback_mentee");

                    b.HasOne("HappyPrograming.Models.Mentor", "Mentor")
                        .WithMany("Feedbacks")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("fk_feedback_mentor");

                    b.HasOne("HappyPrograming.Models.Request", "Request")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("fk_feedback_request");

                    b.Navigation("Mentee");

                    b.Navigation("Mentor");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("HappyPrograming.Models.Mentor", b =>
                {
                    b.HasOne("HappyPrograming.Models.User", "User")
                        .WithOne("Mentor")
                        .HasForeignKey("HappyPrograming.Models.Mentor", "UserId")
                        .IsRequired()
                        .HasConstraintName("fk_mentor_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyPrograming.Models.Request", b =>
                {
                    b.HasOne("HappyPrograming.Models.User", "Creator")
                        .WithMany("Requests")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("fk_request_mentee");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("HappyPrograming.Models.User", b =>
                {
                    b.HasOne("HappyPrograming.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_user_role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MentorRequest", b =>
                {
                    b.HasOne("HappyPrograming.Models.Mentor", null)
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("fk_mentorrequest_mentor");

                    b.HasOne("HappyPrograming.Models.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("fk_mentorrequest_request");
                });

            modelBuilder.Entity("MentorSkill", b =>
                {
                    b.HasOne("HappyPrograming.Models.Mentor", null)
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("fk_mentorskill_mentor");

                    b.HasOne("HappyPrograming.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("fk_mentorskill_skill");
                });

            modelBuilder.Entity("RequestSkill", b =>
                {
                    b.HasOne("HappyPrograming.Models.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("fk_requestskill_request");

                    b.HasOne("HappyPrograming.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("fk_requestskill_skill");
                });

            modelBuilder.Entity("RoleFeature", b =>
                {
                    b.HasOne("HappyPrograming.Models.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .IsRequired()
                        .HasConstraintName("fk_rolefeature_feature");

                    b.HasOne("HappyPrograming.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_rolefeature_role");
                });

            modelBuilder.Entity("HappyPrograming.Models.Mentor", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("HappyPrograming.Models.Request", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("HappyPrograming.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HappyPrograming.Models.User", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Mentor");

                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
